### ISSUE TITLE
happner client needs a way to know when its session is expired.

### ISSUE THREAD

**Issue by JensEggers** [happner/happner-2#171] opened 2019-02-01 12:35 UTC
[TR4127](https://github.com/FieldServer/smc-project-board-issues/issues/185)

None of the existing events fire when a session is expired on the server side as configured  by security profile.

The only way to know is to check for a specific error message the next time the client does something. This is failing silently on SMC cloud leading to a non-responsive page.

Notes:

02/01/19-ENG: adding to TR4127 for SB (H)

02/01/19-CC: This should be assigned to SB on the appropriate repo.
TR4122 (DAB) requires this to continue.

**Comment by southbite** [comment] 2019-10-22 13:38
duplicate of #222

**Closed by southbite** 2019-10-22 13:38 UTC
